package com.ticketmanagement.demo.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

import lombok.extern.slf4j.Slf4j;

/**
 * Test class to demonstrate Lombok functionality
 */
@Slf4j // Adds a logger field named 'log'
public class LombokDemoTest {

    @Test
    void testBuilderPattern() {
        // Using the Builder pattern generated by Lombok
        LombokDemoEntity user = LombokDemoEntity.builder()
                .id(1L)
                .username("jsmith")
                .email("john.smith@example.com")
                .password("securePassword")
                .active(true)
                .build();
        
        // Log using the auto-generated slf4j logger
        log.info("Created user: {}", user);
        
        // Test getters generated by Lombok
        assertEquals(1L, user.getId());
        assertEquals("jsmith", user.getUsername());
        assertEquals("john.smith@example.com", user.getEmail());
        assertTrue(user.isActive());
    }
    
    @Test
    void testEqualsAndHashCode() {
        // Create two identical users
        LombokDemoEntity user1 = LombokDemoEntity.builder()
                .id(1L)
                .username("jsmith")
                .email("john.smith@example.com")
                .build();
        
        LombokDemoEntity user2 = LombokDemoEntity.builder()
                .id(1L)
                .username("jsmith")
                .email("john.smith@example.com")
                .build();
        
        // Test equals and hashCode generated by Lombok
        assertEquals(user1, user2);
        assertEquals(user1.hashCode(), user2.hashCode());
    }
    
    @Test
    void testToString() {
        LombokDemoEntity user = LombokDemoEntity.builder()
                .id(1L)
                .username("jsmith")
                .email("john.smith@example.com")
                .password("securePassword") // This should NOT appear in toString()
                .build();
        
        String toString = user.toString();
        log.info("User toString: {}", toString);
        
        // Password should be excluded from toString due to @ToString(exclude = {"password"})
        assertTrue(toString.contains("id=1"));
        assertTrue(toString.contains("username=jsmith"));
        assertTrue(toString.contains("email=john.smith@example.com"));
        assertFalse(toString.contains("securePassword"));
    }
}
